#!/bin/bash

PROC_NAME=httpd
BIN_PATH=`pwd`/install/bin/httpd
RUN_DEPS="wget"

. ../scripts/include/cmdctl.inc

mode=$1
shift || mode="no_action"

case "$mode" in
  *)
    cmdctl_client_action $mode $*
    ;;
esac

rm -f index.html.1
