#!/bin/bash

set -o errexit

RUNCLIENT_CONNECT=${RUNCLIENT_CONNECT:-0}
RUNCLIENT_EXT=${RUNCLIENT_EXT:-html}

if [ "$RUNCLIENT_CONNECT" != "0" ]; then
    nc localhost 1080
    exit 0
fi

wget localhost:1080/index.$RUNCLIENT_EXT
rm -f index.RUNCLIENT_EXT
