#!/bin/bash

ROOT=`readlink -f ../..`

BENCH_TYPE=${BENCH_TYPE:-1}

. ../scripts/include/cmdctl.inc

if [ $BENCH_TYPE -eq 2 ]; then
    TESTS_FILE=$(readlink -f runbench.tests.all)
elif [ $BENCH_TYPE -eq 3 ]; then
    TESTS_FILE=$(readlink -f runbench.tests.custom)
elif [ $BENCH_TYPE -eq 4 ]; then
    TESTS_FILE=$(readlink -f runbench.tests.tmp)
else
    exit 1
fi

trap "echo Exited!; exit;" SIGINT SIGTERM
RUN_EINSTEIN=1 USE_LOG_DIR=1 V=1 LOG_SUB_DIR=bench ./serverctl restart
sleep 10
cat ${TESTS_FILE} | while read TEST
do
    echo "Running test ${TEST}..."
    ./serverctl udscmd pids dbt setdebugstr "${TEST}"
    ./serverctl udscmd pids dbt taintall
    sleep 3
    ./runtest --port 1080 --host 127.0.0.1 --single ${TEST}
done
exit 0
