#!/bin/bash

ROOT=`readlink -f ../..`

BENCH_TYPE=${BENCH_TYPE:-1}

. ../scripts/include/cmdctl.inc

if [ $BENCH_TYPE -eq 2 ]; then
    TESTS_FILE=$(readlink -f runbench.tests.all)
elif [ $BENCH_TYPE -eq 3 ]; then
    TESTS_FILE=$(readlink -f runbench.tests.custom)
elif [ $BENCH_TYPE -eq 4 ]; then
    TESTS_FILE=$(readlink -f runbench.tests.tmp)
else
    exit 1
fi

trap "echo Exited!; exit;" SIGINT SIGTERM
cat ${TESTS_FILE} | while read TEST
do
    TEST_NO_SLASHES=$(echo ${TEST} | sed 's/\//_/g')
    echo "Running test ${TEST} (${TEST_NO_SLASHES})..."
    RUN_EINSTEIN=1 USE_LOG_DIR=1 V=1 LOG_SUB_DIR="${TEST_NO_SLASHES}" ./serverctl restart
    sleep 8
    ./serverctl udscmd pids dbt setdebugstr "${TEST}"
    ./serverctl udscmd pids dbt taintall
    sleep 2
    ./runtest --port 1080 --host 127.0.0.1 --single ${TEST} || true
done
exit 0
